//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiExamen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Empleado1 = new HashSet<Empleado>();
            this.Empleado_Habilidad = new HashSet<Empleado_Habilidad>();
        }
    
        public int IdEmpleado { get; set; }
        public string NombreCompleto { get; set; }
        public string Cedula { get; set; }
        public string Correo { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public Nullable<int> IdJefe { get; set; }
        public int IdArea { get; set; }
        public byte[] Foto { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual ICollection<Empleado> Empleado1 { get; set; }
        public virtual Empleado Empleado2 { get; set; }
        public virtual ICollection<Empleado_Habilidad> Empleado_Habilidad { get; set; }
    }
}
